spring:
    application:
        name: mini7
    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:sqlite:./src/main/resources/database/resquedb.db
        driver-class-name: org.sqlite.JDBC
        username: admin
        password: admin

